### ISSUE TITLE
Link's should support multiple markdown formats

### ISSUE THREAD

**Issue by fourcolors** [jsarafajr/slackify-markdown#13]
Hey I noticed that links will not allow for formatted markdown ie: if you have markdown like this 

```
~~**_[www.google.com ](www.google.com)_**~~
```
~~**_[www.google.com ](www.google.com)_**~~
This will show up as a plain link. It seems that nested markdown works everywhere else but not for links.

**Comment by jsarafajr** [comment]
Hi @fourcolors, thanks for reporting 👍 I'll look into it next week if there won't be any PRs fixings it until then.

**Comment by fourcolors** [comment]
Awesome, I'll take a stab at it.

**Comment by jsarafajr** [comment]
This case should work when URL has a protocol:
```
~~**_[title](https://www.google.com)_**~~
```
