### ISSUE TITLE
Can't get links to work

### ISSUE THREAD

**Issue by pranavbadami** [jsarafajr/slackify-markdown#22]
Hey, great stuff on this library! One issue I'm having is that I can't get links to work properly.
For example, when I try the library with the example from the README, here's what I see in my console: 
Example:
```
const markdown = `
  # List of items

  * item 1
  * item 2
  * item 3

  [here is an example](https://example.com)
  `;

  console.log(slackifyMarkdown(markdown));
```

Output:
![image](https://user-images.githubusercontent.com/6540790/110873262-5e64b000-829f-11eb-9597-cb563ddde2d1.png)

I'd expect the last line of the output text to read: `<https://example.com|here is an example>`. Any pointers on solving this? 

Here's my version info if it's helpful:
```
"slackify-markdown": {
      "version": "4.1.0",
      "resolved": "https://registry.npmjs.org/slackify-markdown/-/slackify-markdown-4.1.0.tgz",
      "integrity": "sha512-dvGUjHAe78NqISOXh+UwEDdPjxRxyYtxo6iYWCCJfX5Eg4nVP5GrTJfJGonrYVRM1Mor0iO2xnFz2ykBeE9xDQ==",
      "requires": {
        "mdast-util-to-markdown": "^0.6.2",
        "remark-gfm": "^1.0.0",
        "remark-parse": "^9.0.0",
        "remark-stringify": "^9.0.1",
        "unified": "^9.0.0",
        "unist-util-remove": "^2.0.1",
        "unist-util-visit": "^2.0.3"
      }
    },
```
Thanks in advance for any help!

**Comment by krisztian-fl** [comment]
Same here, managed to track it down to an `TypeError: URL is not a constructor` error in the `isURL` helper. In a node console it is working fine, in the browser, it seems to be falling back to the builtin `URL` function. Feels like a naming clash.

**Comment by jsarafajr** [comment]
@krisztian-fl Hi, just to clarify, you use slackify-markdown in the browser, right? Never tried it in the browser by myself.

**Comment by krisztian-fl** [comment]
> @krisztian-fl Hi, just to clarify, you use slackify-markdown in the browser, right? Never tried it in the browser by myself.

@jsarafajr yep, it's being used in frontend code. I'm gonna try aliasing that import and get back to you with the results.

**Comment by krisztian-fl** [comment]
@jsarafajr Here's a rather simple fix, using the builtin URL class: https://github.com/jsarafajr/slackify-markdown/pull/24

**Comment by jsarafajr** [comment]
@krisztian-fl thanks, published a new version with the fix.

**Comment by Meinne1** [comment]
213680a1482cd9147d4e0109e8b4f3344f31383e
