### ISSUE TITLE
Breaking change from 3.1.0 to 4.0.0

### ISSUE THREAD

**Issue by ahermant** [jsarafajr/slackify-markdown#25]
Hi there, 
I am working on semantic-release-slack-bot which uses slackify-markdown as a dependency. 
I would like to bump slackify-markdown from 3.1.0 to 4.3.0 to mitigate a vulnerability in trim< 0.0.3 but I cannot figure what is the breaking change between slackify-markdown 3.1.0 and slackify-markdown 4.0.0
I can only see some dependencies and internal changes. All my tests are passing.
Did I miss something ?

**Comment by jsarafajr** [comment]
Hi @ahermant, in v4 the internal mechanism was rewritten as we switched to a new Remark plugin. I think there shouldn't be breaking changes for the clients of this library. But since we did such a major internal change we made it to be a major version bump.

**Comment by ahermant** [comment]
Perfect, thank you very much for your answer.

Le dim. 30 mai 2021 03 h 48, Eugene Baraniuk ***@***.***> a
écrit :
