### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by KristerL** [jsarafajr/slackify-markdown#36]
Safari does not support regex negative [lookbehind](https://caniuse.com/js-regexp-lookbehind) operator:

That operator is used [here](https://github.com/jsarafajr/slackify-markdown/blob/master/src/slackify.js#L123) and because of that when we open console in safari we get this error:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/25435795/193757186-bf6379b4-2b6a-42c0-925e-4264e8dfdc1a.png">

**Comment by jsarafajr** [comment]
Hi, this library was initially developed for Node environment and was never tested on Safari (at least by me). You may probably try an older version, like v.3.1.0, which had some simpler regexp.

**Comment by rexgarland** [comment]
I also ran into this issue. I created a small PR here: https://github.com/jsarafajr/slackify-markdown/pull/38
